version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: repobackend-app #name of the image
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ../:/app
      - caddy_data:/data
      - caddy_config:/config
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  db-data:
